### PR TITLE
Updates for Julia 0.7

### PR DESCRIPTION
**Pull request by rsrock**
Never knew about this package until now. Only the tests needed updates!

### CODE REVIEW

**Comment by rsrock** [comment]
oh yeah, there's that thing called Travis.  Let me deal with that here...

**Comment by rsrock** [comment]
Give me a break, Tim, it's been a while. 😄

**Comment by rsrock** [comment]
By the way, it doesn't look like Appveyor is active for this repo?  Not sure how much it matters, this code is pretty straightforward.

**Comment by rsrock** [comment]
So even though this is green, don't merge this yet.  It looks like there's an allowed failure on 1.0, and I didn't notice any sign of that on 0.7.  Might as well get that at the same time.

[edit] Ooh, iterators! This is juicier than it looked at first.  I'm surprised that `start` and `next` didn't have a deprecation though.

**Comment by timholy** [comment]
The laugh wasn't a criticism, it was for the witty nature of your comment.

Thanks for tackling this! Really grateful for your help. I will prob. be busy with the hackathon tomorrow but can help out after that if it continues to be troublesome.

**Pull request merged**
