### PR TITLE
Upgrade to 1.0

### PR DESCRIPTION
**Pull request by Liozou**
This supersedes #12 by shamelessly taking all the updates brought by @rsrock - amazing work! - and adding upgrades for the iteration protocol and other stuff.

### CODE REVIEW

**Comment by timholy** [comment]
@Liozou, thanks for this!

One etiquette issue:  it's better to leave @rsrock as the author of the part he did and add your commits to it. But don't worry, I'll compute the diff between this and his PR and generate two commits, giving you credit for your part.

**Comment by Liozou** [comment]
I'm terribly sorry, I didn't know it should be done this way! Let me patch it so that there are only my modifications.
My apologies @rsrock, I'm still a bit new at this and never had to collaborate on different but similar PRs.

**Comment by timholy** [comment]
Incorporated into #14

**Comment by timholy** [comment]
No sweat @Liozou, there's no way to learn this stuff unless someone tells you. I'm just grateful for all your help here!

**Comment by rsrock** [comment]
No worries, and welcome aboard!

As I was poking around with this and trying out `iterator()` definitions like @Liozou, I found something that threw me off.  It turns out that you can entirely delete the iterator definitions, and the tests still pass.  It looks like the `AbstractUnitRange` type in Base has it covered (via `OrdinalRange`, I believe).

@timholy, is there any reason to keep those definitions in here? If the range types are defined in the local module as described in the README, wouldn't that be enough?

I'll have to try a new tool that I just heard about, Rebugger.jl, to figure this one out 😉.

**Comment by timholy** [comment]
If the method can be deleted, let's throw it under the bus.

**Pull request closed without merging**
